### ISSUE TITLE
Bottom navigation add padding to recyclerView

### ISSUE THREAD

**Issue by Dave181295** [amirisback/frogo-recycler-view#25]
Having a bottom navigation , when adding padding to the bottom of the recyclerView we got the last item expended ..
```
<com.frogobox.recycler.widget.FrogoRecyclerView
        android:id="@+id/recycler_categorie_restaurant"
        android:layout_width="0dp"
        android:layout_height="0dp"
        android:layout_marginTop="16dp"
        android:orientation="vertical"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@id/title_categorie_restaurant"
        tools:listitem="@layout/single_item_recycler_restaurant" />
```

How to add a bottom padding in a simple way ? we tried also to make the height wrap content..

**Comment by amirisback** [comment]
Please add clipToPadding="false"

**Comment by amirisback** [comment]
https://github.com/amirisback/frogo-recycler-view/blob/master/app/src/main/res/layout/activity_frogo_rv_list.xml

**Comment by amirisback** [comment]
Sample root for item_list.xml

<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/rl_container"
    android:layout_width="match_parent"
    android:layout_height="@dimen/dimen_button_song_height"
    android:layout_marginLeft="16dp"
    android:layout_marginTop="16dp"
    android:layout_marginRight="16dp"
    android:background="@drawable/ic_reskin_btn_list"
    android:gravity="center_vertical"
    android:orientation="vertical"
    android:paddingStart="@dimen/dimen_button_song_padding_left_right"
    android:paddingEnd="@dimen/dimen_button_song_padding_left_right">

**Comment by amirisback** [comment]
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/rl_container"
    android:layout_width="match_parent"
    android:layout_height="@dimen/dimen_button_song_height"
    android:layout_marginLeft="@dimen/frogo_dimen_16dp"
    android:layout_marginTop="@dimen/frogo_dimen_16dp"
    android:layout_marginRight="@dimen/frogo_dimen_16dp"
    android:background="@drawable/ic_reskin_btn_list"
    android:gravity="center_vertical"
    android:orientation="vertical"
    android:paddingStart="@dimen/dimen_button_song_padding_left_right"
    android:paddingEnd="@dimen/dimen_button_song_padding_left_right">

**Comment by Dave181295** [comment]
Thanks you
